development:
  adapter: postgresql
  encoding: unicode
  database: jaredbeck_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: jaredbeck_test
  pool: 5
  timeout: 5000
